### ISSUE TITLE
Unable to use the Sdk when Central Package Management is enable

### ISSUE THREAD

**Issue by jdevillard** [smapiot/Piral.Blazor.Server#4]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [ ] Did you perform a search in the issues?

## Environment Details and Version

Package Version < 5.X

## Description

When configuring the Central Management Package with th Directory.Packages.props, I'm unable to build the project that use `<Project Sdk="Piral.Blazor.Sdk/0.5.0-preview.8538723932">` because it's reference the package `Piral.Blazor.Shared` using a specific version.

[Description of the bug]

## Steps to Reproduce

1. Create a Project that use the Sdk Piral.Blazor.Sdk/vX
2. Create a Directory.Packages.props a the root of the solution to enable central package management

## Expected behavior

ability to build

## Actual behavior

not able to build with the following error `error NU1008`: 

`Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Piral.Blazor.Shared.`

## Possible Origin / Solution

Change the sdk.targets content to add condition and check if this feature is enable to use the attribute `VersionOverride` instead of `Version` (because the version of shared lib should be tied to version of the SDK).

I've a PR to submit.

**Comment by jdevillard** [comment]
Hum , sorry, I think my explanations are not good.

This idea is not to define the Shared Package centrally, but just to allow the usage of Central Package Management (CPM).

When you start to use central configuration by using a `Directory.Packages.props` at the root of your solution, all your project inherit from this and you should remove the `version` attribute in the csproj for your  `<PackageReference />` element (or use the `versionOverride`. Otherwise you'll have a error when trying to build the project.

If you don't want you can add a Directory.Packages.props near the csproj to disable the Central configuration (by using `ManagePackageVersionsCentrally` to false). But you loose the this capability for your project.

The fact is  : 
 -by using the SDK with `<Project Sdk="Piral.Blazor.Sdk/0.5.0-preview.8538723932">` for example, a Sdk.targets is imported and mixed with the csproj
- So the package Piral.Blazor.Shared is imported by this Sdk.targets into the nuget package for the project
- The developer don't see this package in the csproj and cannot remove or change the `version` attribute, he also cannot change the Sdk.targets because it's readonly (because imported by the sdk)

by changing the Sdk.targets, my goal is just to allow the build in the case the developper want to use the CPM for his solution. But because we use the `VersionOverride` attribute, the `Piral.Blazor.Shared` package will always be the same and in phase with the version of the SDK (and this for each project, if two projects reference differents SDK version, there will have the good shared package) . 
Nothing need to be added by the developer centrally in his global `Directory.Packages.props`

is it more clear? 

Everything on CPM here : https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management

**Comment by FlorianRappl** [comment]
Yes thanks for the explanation - that makes it more clear. I was thinking in a different direction here. Let's get the changes in!

**Comment by FlorianRappl** [comment]
Thanks for the PR - merged and included for 0.5.

Once I'm back from my vacation I'll make the final changes, have the preview out and hopefully release 0.5.
