### ISSUE TITLE
Update Autofac.Extensions.DependencyInjection to v9.0.0 to allow keyed service support

### ISSUE THREAD

**Issue by jdevillard** [smapiot/Piral.Blazor.Server#6]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Allow keyed service support in the Shell.

## Background

When trying to embed my shell in an Aspire Project, I've encountered a issue when hitting the `Builder.build()` with the following exception : `This service descriptor is keyed. Your service provider may not support keyed services`

It seems that an update was done to the [Autofac.Extensions.DependencyInjection](https://github.com/autofac/Autofac.Extensions.DependencyInjection) to support keyed service with DotNet8.

I've forced the NuGet package in my AppShell so everything is ok, but I suggest that this library be updated in the Piral.Blazor.Orchestrator nuget.

**Comment by FlorianRappl** [comment]
THanks for the hint - yeah we can update that!

**Comment by FlorianRappl** [comment]
Part of the next preview release.
